SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

create FUNCTION [dbo].[FN_FORMAT_NUMBER]
(@VALOR NUMERIC(30,10),		--NUMERO A FORMATEAR
@DECIMALES INT= 2,		--DECIMALES A MOSTRAR
@SEP_MILES VARCHAR(1) = ',',	--SEPARADOR DE MILES
@SEP_DECIMALES VARCHAR(1) = '.',--SEPARADOR DE DECIMALES
@PREFIJO VARCHAR(10) = '',	--PREFIJO EJEMPLO '$ ' 
@SUFIJO VARCHAR(20) = '')	--SUFIJO EJEMPLO ' PESOS'
RETURNS VARCHAR(50)
AS
BEGIN

DECLARE
@STR_VALOR_INT VARCHAR(100),
@STR_VALOR_DEC VARCHAR(100),
@STR_VALOR VARCHAR(100),
@STR_MILES VARCHAR(100),
@POS_X INT

-- REDONDEO DECIMALES 
SELECT @VALOR = ROUND(@VALOR, @DECIMALES)

SELECT @STR_VALOR = CONVERT(VARCHAR(100),@VALOR)

--- POSICION DEL PUNTO
SELECT @POS_X = CHARINDEX('.',@STR_VALOR)

IF @POS_X <> 0
BEGIN
	SELECT @STR_VALOR_INT = LEFT(@STR_VALOR, @POS_X -1)
	SELECT @STR_VALOR_DEC = SUBSTRING(@STR_VALOR, @POS_X+1, LEN(@STR_VALOR))
END
ELSE
BEGIN
	SELECT @STR_VALOR_INT = @STR_VALOR
	SELECT @STR_VALOR_DEC = ''
END

SELECT @STR_VALOR_DEC = LEFT(@STR_VALOR_DEC + '0000000000',@DECIMALES)


SELECT @STR_MILES = ''
WHILE NOT @STR_VALOR_INT = ''
BEGIN
	IF LEN(@STR_VALOR_INT) > 3
		BEGIN
		SELECT @STR_MILES = @SEP_MILES + RIGHT(@STR_VALOR_INT,3) + @STR_MILES
		SELECT @STR_VALOR_INT = LEFT(@STR_VALOR_INT, LEN(@STR_VALOR_INT)-3)
		END
	ELSE
		BEGIN
		SELECT @STR_MILES = @STR_VALOR_INT + @STR_MILES
		SELECT @STR_VALOR_INT = ''
		END
END

SELECT @STR_VALOR_INT = @STR_MILES

SET @STR_VALOR = @PREFIJO + @STR_MILES + @SEP_DECIMALES + @STR_VALOR_DEC + @SUFIJO

RETURN RTRIM(@STR_VALOR)
END
---------------------------------------------
-- CARLOS ESQUIVEL campeon_1@hotmail.com  ---
---------------------------------------------

 

GO
